seed: 42
device: cuda

task:
  name: TFBind10-Exact-v0

GP:
  num_functions: 8
  num_points: 1024
  num_gradient_steps: 100
  sampling_from_GP_lr: 0.05
  delta_lengthscale: 0.25
  delta_variance: 0.25
  initial_lengthscale: 6.25
  initial_outputscale: 6.25
  noise: 0.01
  num_fit_samples: 15000
  threshold_diff: 0.001
  type_of_initial_points: highest
  traj_steps: 200

model:
  FM:
    params:
      hidden_dim: 1024
      dropout: 0.15
      ode_steps: 200
    optimizer:
      lr: 0.001

training:
  batch_size: 256
  n_epochs: 150

testing:
  num_candidates: 128
